# Generated by Django 5.2.5 on 2025-08-22 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('bookings', '0001_initial'),
        ('services', '0002_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='received_booking', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='services.service'),
            preserve_default=False,
        ),
    ]
